# Generated by Django 5.0.1 on 2024-05-04 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_seller_seller_upi_alter_seller_license_number_shop'),
        ('orders', '0002_alter_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.AddField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.customer'),
            preserve_default=False,
        ),
    ]
