# Generated by Django 5.0.1 on 2024-05-04 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_cartitems_cart'),
        ('store', '0009_alter_product_expiry_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItems',
            new_name='CartItem',
        ),
    ]
