# Generated by Django 5.0.1 on 2024-04-09 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('name', models.CharField(default='category1', max_length=255)),
                ('description', models.CharField(default='Enter description here', max_length=300)),
                ('category_image', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('originalPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_image', models.ImageField(null=True, upload_to='')),
                ('expiry_image', models.ImageField(upload_to='')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('expire_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('discountedPrice', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category')),
            ],
        ),
    ]
