# Generated by Django 5.0.1 on 2024-03-18 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShoppingItem',
            new_name='Product',
        ),
    ]
