# Generated by Django 5.0.1 on 2024-04-30 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_category_id_remove_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expiry_date',
            field=models.DateField(default=datetime.date(2024, 4, 30)),
        ),
    ]
