# Generated by Django 5.0.1 on 2024-05-04 11:42

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_product_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expiry_image',
            field=models.ImageField(null=True, upload_to=store.models.product_image_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(null=True, upload_to=store.models.product_image_path),
        ),
    ]
