# Generated by Django 5.0.1 on 2024-05-04 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_product_expiry_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 4, 11, 43, 40, 551211, tzinfo=datetime.timezone.utc)),
        ),
    ]
