# Generated by Django 5.0.1 on 2024-04-09 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='seller',
            managers=[
            ],
        ),
    ]
