# Generated by Django 5.0.1 on 2024-04-09 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_seller_groups_alter_seller_user_permissions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='seller_id',
            new_name='user_id',
        ),
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('location_id', models.IntegerField(primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customuser')),
            ],
        ),
    ]
