# Generated by Django 5.0.1 on 2024-04-27 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_is_customer_user_is_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='seller_upi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='license_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='core.seller')),
            ],
        ),
    ]
